### ISSUE TITLE
where to generate theses credentials ? 

### ISSUE THREAD

**Issue by daslicht** [audiomack/audiomack-api-examples#1]
where to generate theses credentials, please ? 
```
'YOUR_AUDIOMACK_KEY',
    'client_credentials_secret'     => 'YOUR_AUDIOMACK_SECRET',

```

~Marc

**Comment by daslicht** [comment]
help please

**Comment by dmacli** [comment]
@daslicht email api@audiomack.com with your use case and we will review your application.

**Comment by daslicht** [comment]
me was tol dthat no api access is granted at all for 3rd party developers.
yay. Meanwhile i built my own Player with full waveform.

**Comment by daslicht** [comment]
What is the purpose of this API if we dont get credentials ?

**Comment by karock** [comment]
credentials are granted by Audiomack on a case-by-case basis.

hosting audio for free use in 3rd party players is not an approved or permitted use of our api.

**Comment by Stephenmiles08** [comment]
Good day sir @dmacli 
I want to make use of Audiomack's API, I have sent an email containing my use case to api@audiomack.com, and still yet to receive a response, is there something I need to do or is there a problem. I need this urgently for my project, that's why I ask. Thanks.

**Comment by daslicht** [comment]
> Good day sir @dmacli I want to make use of Audiomack's API, I have sent an email containing my use case to [api@audiomack.com](mailto:api@audiomack.com), and still yet to receive a response, is there something I need to do or is there a problem. I need this urgently for my project, that's why I ask. Thanks.

Good luck, they told me that they have no interest in 3rd party developers when I asked them.
